### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#104]
With some more path checking we could make this accessible to both Linux and Mac devs.

Then I'll have to look into potential deployment options.

**Comment by rods-honorio** [comment]
Let me try :D

**Comment by alichtman** [comment]
@rods-honorio Off the top of my head, if we just check for the existence of macOS specific paths before trying to back them up, this should be pretty easily doable.

**Comment by alichtman** [comment]
WIP in #183
