### ISSUE TITLE
Make each package manager print in a color that's not the normal log color for reinstallation

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#109]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/20600565/47207180-2e27ba00-d350-11e8-9372-b85bc7e8a994.png">

This look the same, color wise, for both backing up and reinstalling.

**Comment by FilippoGuarda** [comment]
can i work on this?

**Comment by alichtman** [comment]
Go for it, @FilippoGuarda.

**Comment by flaixman** [comment]
Hi, 

What color do you prefer? Green, yellow, or any special color?

**Comment by alichtman** [comment]
@FilippoGuarda @flaixman I'm actually just going to do this one myself since it involves a lot of testing to see what it actually looks like.

**Comment by flaixman** [comment]
> @FilippoGuarda @flaixman I'm actually just going to do this one myself since it involves a lot of testing to see what it actually looks like.

Perfect! Good luck :)

**Comment by alichtman** [comment]
Still need to do reinstallation printing, but back up is done.
