### ISSUE TITLE
Backup Fonts doesn't back up all fonts

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#111]
```python
def backup_fonts(path):
	"""
	Creates list of all .ttf and .otf files in ~/Library/Fonts/
	"""
	print_section_header("FONTS", Fore.BLUE)
	make_dir_warn_overwrite(path)
	print(Fore.BLUE + "Copying '.otf' and '.ttf' fonts..." + Style.RESET_ALL)
	fonts_path = _home_prefix("/Library/Fonts/")
	# TODO: For some reason, this doesn't get all the fonts in fonts_path dir
	fonts = [os.path.join(fonts_path, font) for font in os.listdir(fonts_path) if font.endswith(".otf") or font.endswith(".ttf")]

	# pprint(fonts)
	for font in fonts:
		# print(font, " TO ", os.path.join(path, font.split("/")[-1]))
		if os.path.exists(font):
			copyfile(font, os.path.join(path, font.split("/")[-1]))
```

One solution could be to use `copytree` and then remove all files that don't end in `.ttf` or `.otf`

**Comment by giancarloGiuffra** [comment]
Hi, I would like to work on this.

**Comment by alichtman** [comment]
@giancarloGiuffra, best of luck. Let me know if you have any questions.

**Comment by giancarloGiuffra** [comment]
@alichtman hi again. I have setup my environment and run a backup of the fonts. It got them all actually. Do you have any tip on how to reproduce the bug?

**Comment by alichtman** [comment]
If you run `ls ~/Library/Fonts/` and compare that with what's actually backed up, the lists are different.

**Comment by giancarloGiuffra** [comment]
I see, I actually compared the backup with the fonts in /Library/Fonts and they were exactly the same. So the function is reading from that directory most probably. I will check what the _home_prefix function is doing.

**Comment by alichtman** [comment]
The function is definitely reading from the right directory, since some fonts are copied correctly. 

However, the issue is that not all fonts are copied correctly, and I'm not sure why. The issue is almost definitely not with the `_home_prefix()` function.

**Comment by giancarloGiuffra** [comment]
I left a comment on the PR. The problem was that the path was absolute and how `os.path.join` behaves.
