### ISSUE TITLE
ERROR collecting tests

### ISSUE THREAD

**Issue by FilippoGuarda** [alichtman/shallow-backup#115]
running `python3 -m pytest`
i get this output 
`ImportError while importing test module '/home/watch/gitprojects/shallow-backup/tests/test_copies.py'.  
Hint: make sure your test modules/packages have valid Python names.  
Traceback:  
tests/test_copies.py:4: in <module>  
    from shallow_backup import _copy_file, _copy_dir  
shallow_backup.py:2: in <module>  
    import git  
E   ModuleNotFoundError: No module named 'git'  
`

**Comment by FilippoGuarda** [comment]
okay, issue resolved, my bad

**Comment by alichtman** [comment]
All good, I've made that same mistake before.
