### ISSUE TITLE
Symlink instead of copying files

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#125]
```
    Multi-threading for reinstallation of packages.
    Multi-threading for config backup, just like is done for dot backup
    Not copying atom/sublime/vscode packages
    git clean
```
EDIT: symlinking would be the largest improvement by far. #188

**Comment by 4ndrej** [comment]
Whole backup multithreading should be removed. Doing backup on spinning disc may also conflict with req 1 since spinning disc is not good parallel worker at all

**Comment by Starcode71Ooze** [comment]
let me try?

**Comment by alichtman** [comment]
@4ndrej Most modern computers have SSDs in them, not hard disks. In short: multithreading is a huge performance boost and it should be added.

@Starcode71Ooze go for it, man. If you need any help, let me know.
