### ISSUE TITLE
Add --add & --rm commands to actions menu

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#129]
When a user is shown a menu, the options to add and rm a path from the config should be shown. 

The user should be prompted for a folder and then prompted for a path, and then the correct action should be performed.

The program should exit afterwards.

**Comment by sfriedfertig** [comment]
Hey, I'd like to take a swing at this, but I would like to clarify: do you mean "adding" and "removing" a path as in leaving it out of the backup?

**Comment by alichtman** [comment]
> as in editing the config file

Yep, so I've already written the implementation for --add and --rm as CLI args. All that's needed is access to them in the CLI.

It should work like this:

1. Add an option to the actions menu to edit the config fie.
2. Display the config
3. Ask whether they'd like to add or remove a path.
    - If they're adding a path, prompt them for a subfolder and then the path.
    - If they're removing a path, they should have a selection of paths they can remove.
4. Bring them back to the action menu. (This may require a little refactoring.)

```


```

**Comment by alichtman** [comment]
NOTE: Wait for #157 to be merged in before working on this.

**Comment by alichtman** [comment]
It would be cool if we printed example formatting to clearly show the user how to enter the path.
