### ISSUE TITLE
Refactor --rm to take a single path arg

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#130]
`--rm FOLDER PATH` is not as user friendly as it could be.

It should really just be `--rm PATH` and we can search all of the config for the path.

**Comment by kishan3** [comment]
Hi, Which folder is this command located?

**Comment by alichtman** [comment]
You should search the whole config to find the folder with the path in it.

**Comment by alichtman** [comment]
Done in f26ff83
