### ISSUE TITLE
Replace colorama with escape codes

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#137]
No need for the extra dependency.

```
# ASCII color codes
GREEN = '\033[92m'
GRAY = '\033[90m'
CYAN = '\033[36m'
RED = '\033[31m'
YELLOW = '\033[33m'
END = '\033[0m'
UNDERLINE = '\033[4m'
BOLD = '\033[1m'
```

**Comment by Hax7** [comment]
Hi, can you give some extra info? I would like to work on this but I don't understand the issue

**Comment by redpfire** [comment]
I'm gonna work on it. Will PR soon.

**Comment by alichtman** [comment]
@redpfire perfect.

@Hax7 Take a look at ASCII Color Codes, and the source code for Colorama and then let me know if it's still unclear.

**Comment by alichtman** [comment]
jk we need this for Windows compatibility, my bad.
