### ISSUE TITLE
Failing npm Reinstall

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#148]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/20600565/47604610-c44b8800-d9c1-11e8-97ee-8f6d24ed6a08.png">

**Comment by tim-coutinho** [comment]
This has to do with the way `subprocess.run` handles pipes. See https://security.openstack.org/guidelines/dg_avoid-shell-true.

The way `run_cmd_write_stdout` and `run_cmd` handle input and output will have to be refactored, or another function added along the lines of `run_cmd_return_stdout` that handles chaining piped commands.

**Comment by alichtman** [comment]
Addressed in #299
