### ISSUE TITLE
Option to add ssh keys when they're reinstalled

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#150]
At the moment, when ssh keys are reinstalled, they're not "usable."

I'm not sure what the best way to set this up is, but all keys that were added to the ssh daemon should be re-added.

`ssh-add ~/.ssh/id_rsa` is the command for adding the `id_rsa` key on a mac.

Need to consider cross-platform usage too.

**Comment by alichtman** [comment]
This will trip inexperienced users up, and I want this tool to be really user friendly. This is a critical feature to get right.

**Comment by alichtman** [comment]
It's just occurred to me that it's possible this is a bug specific to my environment and not caused by `shallow-backup`. Can anyone reproduce this?

**Comment by petedreizehn** [comment]
is this still something to do?
If so I would test this on my linux machine (Debian 10) and look into it.
Usually for most linux distributions ```ssh-add``` is the command to go. What actually means not usable in your description?

**Comment by alichtman** [comment]
Yeah, this is still something I want to so. Whenever an ssh key is "reinstalled," it should be added to the ssh agent.

**Comment by alichtman** [comment]
nvm, I screwed something up on my laptop. Nothing is wrong with the software lmao
