### ISSUE TITLE
Use --yes click option for confirmation to delete the backup.

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#152]
Example from Click docs:

```python
@click.command()
@click.option('--yes', is_flag=True, callback=abort_if_false,
              expose_value=False,
              prompt='Are you sure you want to drop the db?')
def dropdb():
    click.echo('Dropped all tables!')
```

**Comment by 0az** [comment]
Mind if I work on this?

**Comment by alichtman** [comment]
Your take might be correct. I didn't look too closely at possible implementations for this before opening the issue.

The real question is whether we actually want a "delete backup" confirmation prompt shown if the delete arg is used on a CLI, and I don't think we do. 

Reopen this if you have a strong opposing view, but my thinking is that `--remove`, or whatever the flag is named, is enough of a confirmation that accidental deletion should be impossible.
