### ISSUE TITLE
Refactor version printing in CLI with Click

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#159]
Here's a good example

```python
def print_version(ctx, param, value):
    if not value or ctx.resilient_parsing:
        return
    click.echo('Version 1.0')
    ctx.exit()

@click.command()
@click.option('--version', is_flag=True, callback=print_version,
              expose_value=False, is_eager=True)
def hello():
    click.echo('Hello World!')
```

**Comment by alichtman** [comment]
I'm actually not sure this makes sense to change. The way it's engineered at the moment works fine for both the `-v` arg and the CLI splash screen. Let's just leave this as it is.

**Comment by nunomdc** [comment]
Can we at least make it so both "-v" and "--version" work to print the version information?

**Comment by alichtman** [comment]
Yep, this should be as easy as adding `--version` to the click option.

Open a PR and I'll merge it. 

@nunomdc
