### ISSUE TITLE
KeyError: 'sublime2' when creating a backup

### ISSUE THREAD

**Issue by AlexanderProd** [alichtman/shallow-backup#202]
Seems like I'm on a bug hunting streak today, while attempting to create the first backup of my machine I've encountered this error. 

```
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/__main__.py", line 129, in cli
    backup_all(dotfiles_path, packages_path, fonts_path, configs_path)
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/backup.py", line 199, in backup_all
    backup_packages(packages_path, skip)
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/backup.py", line 144, in backup_packages
    sublime_2_path = os.path.join(config_paths["sublime2"], "Packages")
KeyError: 'sublime2'
``` 
This happened after it backuped Atom. 

I don't have sublime2 or another sublime installed on my machine. 
I'm using the shallow-backup version that fixes #200 . 

Python version: 3.7.1
pip3: 18.1
macOS: 10.14.2

**Comment by alichtman** [comment]
Hmm. This error should not be possible...

Can you provide your configuration file? (Located at `~/.shallow-backup`)

**Comment by AlexanderProd** [comment]
Sure, this is the content of my configuration file. 

```
{
    "backup_path": "~/shallow-backup",
    "dotfiles": [
        ".bashrc",
        ".bash_profile",
        ".gitconfig",
        ".profile",
        ".pypirc",
        ".shallow-backup",
        ".vimrc",
        ".zlogin",
        ".zprofile",
        ".zshrc"
    ],
    "dotfolders": [
        ".ssh",
        ".vim"
    ],
    "default-gitignore": [
        "dotfiles/.ssh",
        "dotfiles/.pypirc"
    ],
    "config_mapping": {
        "/Users/alexanderhoerl/Library/Application Support/Sublime Text 2": "sublime2",
        "/Users/alexanderhoerl/Library/Application Support/Sublime Text 3": "sublime3",
        "/Users/alexanderhoerl/.atom": "atom",
        "/Users/alexanderhoerl/Library/Preferences/com.apple.Terminal.plist": "terminal_plist"
    }
}
```

I've checked my Application Support directory and I don't have any Sublime text folder there.

**Comment by alichtman** [comment]
Alright, I'm getting the same error now. I don't know why this didn't happen during any of my testing or the demo...

I can look through the git history to see when this error was introduced, but to solve it, I'm just going to remove the ability to back up a list of installed Sublime [2/3] packages. It's redundant, since I'm backing up the entirety of the Sublime folder in the configs backup.

Changes being pushed to a testing branch for you in a moment.

**Comment by alichtman** [comment]
https://github.com/alichtman/shallow-backup/tree/key-error-fixes

Note: This is completely untested (and therefore not on `master`.)

If it fixes this issue for you, lmk and I'll merge it in.

**Comment by AlexanderProd** [comment]
I've just tried it and it works now!

**Comment by alichtman** [comment]
Perfect. I'll merge this in and push a new version to PyPi.
