### ISSUE TITLE
Backup pip3 packages

### ISSUE THREAD

**Issue by AlexanderProd** [alichtman/shallow-backup#211]
I'm wondering why this hasn't been requested yet but theres no backup of pip packages at the moment.

**Comment by alichtman** [comment]
```python
# pip
print_pkg_mgr_backup("pip")
command = "pip list --format=freeze"
dest = "{}/pip_list.txt".format(backup_path)
	run_cmd_write_stdout(command, dest)
```

Yes, there is.

**Comment by AlexanderProd** [comment]
Oh sorry I didn't realize that, but it seems like I've got a bug then because shallow-backup never backuped any pip packages on my local machine

**Comment by alichtman** [comment]
Hmm. Are you sure you use pip and not pip3?

**Comment by alichtman** [comment]
Just tested this out and I've got a pip backup.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/20600565/50728983-b4ee6680-10f7-11e9-9a08-2998c30b11df.png">

**Comment by AlexanderProd** [comment]
Oh yeah you’re right I’m using pip3 not pip. I guess we should add pip3 backup then though.

**Comment by alichtman** [comment]
I leave issues open until fixes are merged in.
