### ISSUE TITLE
Error when reinstalling all

### ISSUE THREAD

**Issue by AlexanderProd** [alichtman/shallow-backup#216]
When trying to reinstall all from the main menu I'm getting the following error seems like there's a problem with paths and directories. 

I've been using version 2.3 

```
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/__main__.py", line 159, in cli
    reinstall_all_sb(dotfiles_path, packages_path, fonts_path, configs_path)
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/reinstall.py", line 129, in reinstall_all_sb
    reinstall_dots_sb(dotfiles_path)
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/reinstall.py", line 26, in reinstall_dots_sb
    copyfile(file, home_path)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/Users/alexanderhoerl'
```

**Comment by alichtman** [comment]
Hmm. I'll look into this as soon as I have time. Looks like an error introduced in the last version, maybe?

**Comment by AlexanderProd** [comment]
I've just tried it in version 2.2 and the bug happens there as well with the same error message.

**Comment by alichtman** [comment]
Related to #209?

**Comment by AlexanderProd** [comment]
I guess not because I don’t have any sublime text backups.

**Comment by alichtman** [comment]
Well, it's not necessarily specific to the backup. The root of the issue is that a copying function call fails.

**Comment by AlexanderProd** [comment]
Oh yeah you're right I guess they have the same root. Does reinstalling all work for you?

**Comment by alichtman** [comment]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/20600565/51072390-a509e180-1625-11e9-9761-a9e35767d30b.png">

Yep, I get the same error. It's a bit weird because the error is thrown on a line that should be impossible to hit with this code. `Err: Is a directory` but thrown on a line that can only be hit if the path is *not* a directory.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/20600565/51072399-c1a61980-1625-11e9-952c-fefc31e56541.png">

**Comment by robbixc** [comment]
Hey :) any news on this? I also hit the bug. I'm on ubuntu 18.04

**Comment by alichtman** [comment]
@robbixc Unfortunately, I haven't had any time to work on this. I likely won't have any time for the foreseeable future, either. I'd like to bring on another maintainer for this project... But that's a conversation for a different thread. 

Short answer is: no progress.

**Comment by heysupratim** [comment]
Hey just informing that this issue still exists on 3.2

**Comment by alichtman** [comment]
Happy to review a PR for this if you put one together. I don't have time to resolve this bug at the moment, and it doesn't interfere with my workflow, so it's not high priority for me. @heysupratim

**Comment by heysupratim** [comment]
Hope this helps 🤗
