### ISSUE TITLE
Backup brew tap 

### ISSUE THREAD

**Issue by satnami** [alichtman/shallow-backup#218]
I think `brew tap` list would be needed in case I downloaded formula from third-party repositories like (GitHub).

**Comment by alichtman** [comment]
Yeah, this is a good call.

Changes should be made both in `backup.py` and `reinstall.py`

Want to open a PR?

**Comment by ashley-woodard** [comment]
I plan on looking at this sometime before June. In the meantime, I think its worth pointing out [Homebrew Bundle](https://github.com/Homebrew/homebrew-bundle) let’s you specify taps, casks, and MAS apps on top of regular brew packages all in one file. This is the solution I’ll probably end up hacking together soon. I would be glad that I throw together a PR at some point but it may be a few weeks. Thoughts, comments, suggestions? Let me know. Cheers.

**Comment by alichtman** [comment]
Yep, I like that approach. It would be great if you submitted a PR. Looks
like the command we should run is: $ brew bundler dump. Then maybe just
move the file into the backup. And we can also remove the code that creates
the “brew_list” file.

**Comment by satnami** [comment]
Sorry @alichtman I'm not that much in python, so I'll leave it to @ashley-woodard

**Comment by alichtman** [comment]
@ashley-woodard Any update on this?

**Comment by cocoonkid** [comment]
Yes please, that would be a great addition. If it weren't over my pay grade (yet) I'd do it myself.
Shallow Backup is the best tool out there! It deserves more love.

**Comment by WorkInProgress-Development** [comment]
Just wondering what the hold up is for merging #294?
Again, thanks for a wonderful tool.

**Comment by alichtman** [comment]
@WorkInProgress-Development It's difficult to find time to maintain open source projects, excel in my professional full-time dev job and do what I want with my personal life.

**Comment by WorkInProgress-Development** [comment]
I understand.
I was just wondering if there was anything that needed testing or something, because of "Good to go after this change." on the pull request.

Anyways, thank you for an amazing tool, and I hope I haven't been cruel.

**Comment by alichtman** [comment]
Nah, that wasn't directed harshly at you. Just something I've been thinking about a lot ever since I (unintentionally) stepped back from open source. 

From a technical standpoint, #292 and #294 touch a lot of the same code are a difficult to merge since I'm anticipating merge conflicts / regressions, and don't particularly want to deal with them right now.

**Comment by alichtman** [comment]
@WorkInProgress-Development Done. Thanks for being patient.

**Comment by cocoonkid** [comment]
@alichtman Thanks for your commitment.
