### ISSUE TITLE
Back up fonts directory 

### ISSUE THREAD

**Issue by chshbh** [alichtman/shallow-backup#219]
Is there fall back for the default font directory? 
![image](https://user-images.githubusercontent.com/9166890/51849524-e7316380-2345-11e9-93f1-744c5ebff603.png)

Since, I dont have the font directory it scans the fonts for, should it not look at the fonts at system's location (/usr/share/fonts/)?

**Comment by alichtman** [comment]
That’s a good catch. If you open a PR, I’ll certainly merge it in to fix this up.

**Comment by chshbh** [comment]
#217 fixes this.
