### ISSUE TITLE
Similar(ish) project to be aware of?

### ISSUE THREAD

**Issue by jasikpark** [alichtman/shallow-backup#220]
https://github.com/mxcl/Workbench/

The one thing I really appreciate about Workbench is that it bypasses the privacy problem. It is sad that it's not cross-platform or cross-mac but it is good.

**Comment by alichtman** [comment]
It's a cool project, and I like the GUI a lot. I think that's the one core feature that shallow-backup is missing. 

We could maybe fix the privacy problem by encrypting when pushing to github.
