### ISSUE TITLE
How do you backup minus the shallow-backup repo?

### ISSUE THREAD

**Issue by atanasj** [alichtman/shallow-backup#225]
Hi, 

This is a query more than an issues... How do I am using Time Machine to backup my mac. How do I exclude the `shallow-backup` repo from my regular backups?

Thanks,
Atanas.

**Comment by alichtman** [comment]
My question is: Why would you want to? It's a few `KB`s. Redundancy in backups is a good thing. I include my `shallow-backup` directory in my TimeMachine backups.

Otherwise, this is probably a question for macOS stack exchange or something. Google "exclude directory from TimeMachine backup"

**Comment by atanasj** [comment]
No worries, thanks.
