### ISSUE TITLE
Add Support for Hammerspoon dotfolder

### ISSUE THREAD

**Issue by heysupratim** [alichtman/shallow-backup#244]
Hammerspoon is an open-source automation framework for mac that uses Lua scripting and it stores its user-made scripts in the `.hammerspoon `directory under the user `home` directory.

For reference see[ hammerspoon.org/](hammerspoon.org/)

**Comment by alichtman** [comment]
If you would like this to be backed up, just modify your config file to include this dotfolder. If you're suggesting to have this backed up by default, feel free to open a PR.
