### ISSUE TITLE
Setting backup path to ~/.shallow_backup breaks subsequent runs

### ISSUE THREAD

**Issue by ThatsJustCheesy** [alichtman/shallow-backup#265]
I wanted my backup to be hidden, so I innocuously specified `~/.shallow-backup` as my backup dir. The first backup ran fine, but subsequent runs spit out this message that explains the "what" but not the "why":

    ERROR: /Users/ian/.shallow-backup is a directory, when we were expecting a file. Manual intervention is required.

This is apparently triggered by [config file migration](https://github.com/alichtman/shallow-backup/blob/fab050d29bd87ce856809014e051d42de3db0328/shallow_backup/upgrade.py#L45). If this code needs to remain for the forseeable future, then `~/.shallow-backup` should probably be forbidden as a backup path.

**Comment by alichtman** [comment]
Yep, this seems like an unintended consequence of the config file migration.

I think that removing this set of lines will solve the problem: https://github.com/alichtman/shallow-backup/blob/fab050d29bd87ce856809014e051d42de3db0328/shallow_backup/upgrade.py#L44-L46
