### ISSUE TITLE
fonts with spaces in filename are not backed up.

### ISSUE THREAD

**Issue by amirtal-cp** [alichtman/shallow-backup#280]
shallow-backup v5.0.1 
macOS catalina (10.15.4)

fonts with spaces in filename are not backed up.
for example:
font filename 'Roboto Mono Nerd Font Complete.ttf' is not backed up.
renaming the font file to 'RobotoMonoNerdFontComplete.ttf' causes it to be included in backup.

**Comment by alichtman** [comment]
Almost definitely an issue relating to quoting the file name before copying it. I’m happy to review a PR. Should be a simple fix in backup.py.

**Comment by amirtal-cp** [comment]
sorry, but i cannot re-produce.
might have been a local issue.

thanks for the quick reply though.
