### ISSUE TITLE
clarify install instructions

### ISSUE THREAD

**Issue by CouldBeThis** [alichtman/shallow-backup#283]
Hello, 

readme.md describes installation:

> 1. Install with [`pip3`](https://pypi.org/project/shallow-backup/)
>    - `$ pip3 install shallow-backup`
>    - `$ shallow-backup`
> 2. Download the `shallow-backup` binary from Releases tab.

A bit confusing. I *think* those items are 2 different (mutually exclusive) options, however the usual list of a numbered list is to present sequential steps. 

just some feedback :)

**Comment by alichtman** [comment]
Yeah, good point. Happy to accept a PR rephrasing those as two alternate installation methods.
