### ISSUE TITLE
Branch support?

### ISSUE THREAD

**Issue by Kabouik** [alichtman/shallow-backup#296]
Does `shallow-backup` allow managing several branches to keep multiple file versions backed up for different machines? I have machines that would mostly use the same dotfiles but need slight differences in others (i.e., depending on resolution, keyboard layout, performance).

I am sorry for opening an issue for this but I haven't found an answer in the help of the program or in the README, I hope I didn't just miss it.

**Comment by alichtman** [comment]
I haven't explicitly built this feature, but it might happen to work if you manage your branches manually. Happy to review a PR, though

**Comment by Kabouik** [comment]
If I understand correctly, the workflow would be to manually create multiple branches in the git repository first, but how would I tell `shallow-backup` to use a given branch? 

As you saw, I am having another issue (#229) for my first backup so I couldn't experiment. Unfortunately I'm afraid I cannot submit a PR anyway because I don't know how to code in Python.

**Comment by alichtman** [comment]
That functionality would have to be added in. It would be a command line arg, like `--branch` or something.

**Comment by alichtman** [comment]
Hey @Kabouik, Conditional Backup and Reinstall should take care of what you're trying to do!

https://github.com/alichtman/shallow-backup#conditional-backup-and-reinstallation
