### ISSUE TITLE
VSCode Backup

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#45]
`~/.vscode/extensions`

and also config files.

**Comment by AlexanderProd** [comment]
I've created a list with files and directories on MacOS that are important to backup.

```
~/Library/Application Support/Code/User/settings.json
~/Library/Application Support/Code/User/syncLocalSettings.json

```
It seems like these settings are all you need to get your user settings back. 

Extensions are saved in 
`/Users/alexanderhoerl/.vscode/extensions
`
Every extension has its own folder with a name like `dbaeumer.vscode-eslint-1.7.2` maybe we can create a list of installed extensions just from the folder names.
