### ISSUE TITLE
Add -configs backup option

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#58]
`-configs` options that would back up app and system configs? So, sublime text settings as well as terminal settings, etc.

**Comment by schilli91** [comment]
I've implemented this feature in an extra branch, but I'm not able to push my branch in order to create a PR. Could you provide permissions to create feature branches?

**Comment by alichtman** [comment]
Hey @schilli91! Thanks for contributing.

Try forking this repository, pushing your branch and opening a Pull Request.

**Comment by schilli91** [comment]
Done. #63
