### ISSUE TITLE
No module named configparser

### ISSUE THREAD

**Issue by emilianos** [alichtman/shallow-backup#60]
I'm getting the following error, I think it has to do with python version rename but can't figure it out.
Happening in 2 different computers.

```
> shallow-backup
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 7, in <module>
    from shallow_backup import cli
  File "/usr/local/lib/python2.7/site-packages/shallow_backup.py", line 9, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by alichtman** [comment]
Try using `python3` and then running `pip3 install configparser`

**Comment by emilianos** [comment]
thank you @alichtman 
besides pip3 i also had to work around .bash_profiles since I had 2 versions of python (3.6 and 3.7)...
it's fixed now 😄
