### ISSUE TITLE
It doesn't backup global npm packages?

### ISSUE THREAD

**Issue by NightMachinary** [alichtman/shallow-backup#61]
The program needs to run `npm ls --parseable=true -g` instead of just `npm ls --parseable=true ` to list global packages.

**Comment by alichtman** [comment]
That sounds right to me. Want to open a PR? @NightMachinary

**Comment by NightMachinary** [comment]
Then what does it backup from npm?!

**Comment by alichtman** [comment]
Honestly, I'm not really a node developer and don't work with npm that much.

It looks like it backs up local node modules (so, goes up through the file tree until it finds a `node_modules` directory and backs up whatever is in that.) 

That's an oversight on my part, and should be fixed.

**Comment by kamidipreetham** [comment]
Can I work on this ?

**Comment by alichtman** [comment]
Go for it, @kamidipreetham.

I think the correct fix was suggested by @NightMachinary, so try that out and see if it solves the bug.
