### ISSUE TITLE
Testing Suite

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#69]
A testing suite would be great to have here. 

It should test all basic functionality, and make sure all files are backed up correctly.

I'd like to use `pytest` for testing.

**Comment by jasikpark** [comment]
http://blog.fizyk.net.pl/blog/running-python-tests-on-traviss-osx-workers.html

**Comment by pyasi** [comment]
Put up a PR to start this off. Happy for feedback on my approach/suggestions for more testing.

**Comment by alichtman** [comment]
Just gave it a look -- great work, @pyasi! Leaving some feedback for you, and then we can get it merged in soon.
