### ISSUE TITLE
Automatically create .gitignore to protect private files

### ISSUE THREAD

**Issue by jasikpark** [alichtman/shallow-backup#71]
If you were to backup your shallow-backup to github, it would be important for `dotfiles/.ssh` to be added automatically to `.gitignore`, and, in my opinion, `packages/installed_apps_list.txt` would be as well, because that's more related to private device use than development use.

I would say that backing up to Github should be a public action, and therefore the data from the shallow-backup that is sent should all be very public information.

Of course, users can edit the `.gitignore` file all they want, but it should be communicated to them that they are potentially uploading sensitive information to the public internet.

For example, here's my shallow-backup on github: 
https://github.com/jasikpark/caleb-jasik-shallow-backup

**Comment by alichtman** [comment]
> in my opinion, packages/installed_apps_list.txt would be as well, because that's more related to private device use than development use.

Now that I think about it, there might be some security concerns with making the list of software you have downloaded public. Let's say there's a vulnerability disclosed publicly in `abc v12.3` software that also happens to be available for download on Homebrew. An attacker can now search GitHub for users that have (or, had at one point) installed the vulnerable version of that software and target them explicitly.

For that reason, I think the only "public by default" items we should have are dotfiles (`.zshrc`, `.vimrc`, etc) and fonts.

**Comment by jasikpark** [comment]
That's very true. What would probably work best is to rework it where the generated folder has the backed up data divided into `public` and `private` folders, with explicit instructions for how to back up just the public one to github or the whole backup to a private storage solution
