### ISSUE TITLE
Rename "configs" directory to "app_configs" 

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#82]

**Comment by adrianocanofre** [comment]
Can you give more information?

**Comment by goblinqueen** [comment]
I kind of guessed what you meant by this issue (see PR), let me know if I got it wrong

**Comment by alichtman** [comment]
You were dead on, @goblinqueen. One minor change and we'll close this up.

**Comment by alichtman** [comment]
My apologies, I'm actually not going to go this route. Updated issue #86
