### ISSUE TITLE
Backup Jetbrains IDE Configs

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#87]
- [ ] CLion
- [ ] Pycharm CE
- [ ] IntelliJ Idea
- [ ] IntelliJ
- [ ] PHPStorm

**Comment by Brand-Temp** [comment]
I'd love to have a shot at this if no one else is yet?

**Comment by alichtman** [comment]
Sure, go for it, @Brand-Temp.

These should be backed up in a subdirectory in the `configs` folder.

**Comment by Brand-Temp** [comment]
Sure thing. How should backups be made if there are config directories for multiple versions of Pycharm or CLion? Should it do all of them, or the most recent, or ask which version you'd like from what you've got, etc?

**Comment by alichtman** [comment]
> Should it do all of them, or the most recent, or ask which version you'd like from what you've got, etc?

I think we should only back up the most recent version. Using outdated software is an edge case I'm comfortable not covering.

**Comment by schilli91** [comment]
> * [ ]  CLion
> * [ ]  Pycharm CE
> * [ ]  IntelliJ Idea
> * [ ]  IntelliJ

I would also add PHPStorm to the list.

**Comment by alichtman** [comment]
Added.
