### ISSUE TITLE
Running error when built from source?

### ISSUE THREAD

**Issue by jasikpark** [alichtman/shallow-backup#92]
1. So I cloned https://github.com/jasikpark/shallow-backup, which is even with this repository
2. set my python version to `v3.6.6`
3. used `pipenv install` to install all of the dependencies described in `Pipfile`,
4. and then ran `pipenv shell` to drop into the virtualenv that would allow me to work with those dependencies.
5. then I ran `python -V` to make sure I was still using `v3.6.6`, which was still true,
6. then I ran `python setup.py develop` to generate the symlinked built script, which ran with success,
7. and then I tried to actually run `shallow-backup`.

This was my result:

[shallow-backup-log.txt](https://github.com/alichtman/shallow-backup/files/2492550/shallow-backup-log.txt)

<img width="1392" alt="screenshot 2018-10-18 10 27 43" src="https://user-images.githubusercontent.com/10626596/47166260-5916fd00-d2c1-11e8-9b7e-355e2a2675d4.png">

**Comment by jasikpark** [comment]
oh no... it's actually 16 commits behind, let me pull from master and try again.

**Comment by jasikpark** [comment]
Yep, still confused.
<img width="1392" alt="screenshot 2018-10-18 10 38 38" src="https://user-images.githubusercontent.com/10626596/47166535-05f17a00-d2c2-11e8-9098-c25392f729bf.png">

**Comment by jasikpark** [comment]
Ok, so deleting `~/.shallow_backup` fixed that problem, but now it's complaining about the new `.gitignore` code.

<img width="1392" alt="screenshot 2018-10-18 10 44 51" src="https://user-images.githubusercontent.com/10626596/47166913-db53f100-d2c2-11e8-9979-88e6aea65520.png">

**Comment by alichtman** [comment]
Try killing all the config files and all the backup dirs and starting fresh
and let me know if you have any issues with that. I made some minor bug
fixes in the PR I merged in last night.

**Comment by jasikpark** [comment]
Ok, so I deleted all of the config files and backup directories and deleted the clone of jasikpark/shallow-backup. It works now, though it still has the default directory as `DEFAULT`

**Comment by alichtman** [comment]
Fixed in #93.

Merging git updates into master now, and then this will be fixed.
