### ISSUE TITLE
Add -delete_backup argument to remove backup dir

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#95]
Look up backup path in config file and remove it.
Also add this to the interactive menu.

**Comment by smartfin** [comment]
Hi. I'm wondering if you are looking to remove previous existed backup dir before writing new backup to it? 
So, user can run ` shallow-backup -cleanup ~/shallow-backup-dir` and  just remove old directory without creating new one?

**Comment by alichtman** [comment]
No, what this flag should do is just remove the directory. 

> I'm wondering if you are looking to remove previous existed backup dir before writing new backup to it?

This functionality exists by default.
