### ISSUE TITLE
On backup path update, the .git folder should be moved.

### ISSUE THREAD

**Issue by alichtman** [alichtman/shallow-backup#97]

**Comment by pyasi** [comment]
I'll take this. So a user wants to update their backup path and we move the .git folder to the new path? Do we want to keep their old paths .git configs?

**Comment by alichtman** [comment]
Yep, we should preserve the .git config (and the way we're going to do that is by literally moving the `.git/` directory.)

**Comment by pyasi** [comment]
https://github.com/alichtman/shallow-backup/pull/99
